version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: diplomatic_db
      http_proxy: http://proxy.cs.ucy.ac.cy:8008/
      https_proxy: http://proxy.cs.ucy.ac.cy:8008/
      HTTP_PROXY: http://proxy.cs.ucy.ac.cy:8008/
      HTTPS_PROXY: http://proxy.cs.ucy.ac.cy:8008/
    command: mongod --port 27017 --nojournal --profile 0 --setParameter diagnosticDataCollectionEnabled=false
    expose:
      - 27017
    volumes:
      - ./mongoDB/database:/data/db
    restart: unless-stopped
    ports:
      - "27017:27017"
    logging:
      driver: "none"
    dns: <DNS server IP>

  db_monitor:
    container_name: db_monitor
    build: ./db_monitor
    depends_on:
      - mongodb
    environment:
      PYTHONUNBUFFERED: 1
      http_proxy: http://proxy.cs.ucy.ac.cy:8008/
      https_proxy: http://proxy.cs.ucy.ac.cy:8008/
      HTTP_PROXY: http://proxy.cs.ucy.ac.cy:8008/
      HTTPS_PROXY: http://proxy.cs.ucy.ac.cy:8008/
    dns: <DNS server IP>

  # fasterrcnn_mobilenet_v3_large_320_fpn, fasterrcnn_mobilenet_v3_large_fpn, fasterrcnn_resnet50_f retinanet_resnet50_fpn, maskrcnn_resnet50_fpn
  cloud:
    container_name: cloud
    build: ./cloud
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 1
      ML: 'maskrcnn_resnet50_fpn'
      Port: 5000
      http_proxy: http://proxy.cs.ucy.ac.cy:8008/
      https_proxy: http://proxy.cs.ucy.ac.cy:8008/
      HTTP_PROXY: http://proxy.cs.ucy.ac.cy:8008/
      HTTPS_PROXY: http://proxy.cs.ucy.ac.cy:8008/
    depends_on:
      - db_monitor
    dns: <DNS server IP>

  edge1:
    container_name: edge1
    build: ./edge
    ports:
      - "5001:5001"
    environment:
      PYTHONUNBUFFERED: 1
      ML: 'retinanet_resnet50_fpn'
      Port: 5001
      http_proxy: http://proxy.cs.ucy.ac.cy:8008/
      https_proxy: http://proxy.cs.ucy.ac.cy:8008/
      HTTP_PROXY: http://proxy.cs.ucy.ac.cy:8008/
      HTTPS_PROXY: http://proxy.cs.ucy.ac.cy:8008/
    depends_on:
      - cloud
    dns: <DNS server IP>

  edge2:
    container_name: edge2
    build: ./edge
    ports:
      - "5002:5002"
    environment:
      PYTHONUNBUFFERED: 1
      ML: maskrcnn_resnet50_fpn
      Preprocessing: BW,1,resize,25%,quality,25%
      Port: 5002
      http_proxy: http://proxy.cs.ucy.ac.cy:8008/
      https_proxy: http://proxy.cs.ucy.ac.cy:8008/
      HTTP_PROXY: http://proxy.cs.ucy.ac.cy:8008/
      HTTPS_PROXY: http://proxy.cs.ucy.ac.cy:8008/
    depends_on:
      - cloud
    dns: <DNS server IP>

  workload:
    container_name: workload
    build: ./workload
    depends_on:
      - cloud
    environment:
      PYTHONUNBUFFERED: 1
      Edges: edge1,edge2
      Images: 5
      Sleep: 20
      http_proxy: http://proxy.cs.ucy.ac.cy:8008/
      https_proxy: http://proxy.cs.ucy.ac.cy:8008/
      HTTP_PROXY: http://proxy.cs.ucy.ac.cy:8008/
      HTTPS_PROXY: http://proxy.cs.ucy.ac.cy:8008/
    dns: <DNS server IP>

# mongoseed:
#   image: mongo
#   container_name: mongoseed
#   volumes:
#     - ./mongoDB/init:/init
#   command: mongoimport --host mongodb --db diplomatic_db --collection col
#     --jsonArray --file /init/init.json && python3 /init/db_monitor.py
#   depends_on:
#     - mongodb
