version: "3"
#make sure preferences no comma last
services:

  workload:
    container_name: workload
    build: ./workload
    # depends_on:- cloud
    environment:
      PYTHONUNBUFFERED: 1
      Edges: edge1,edge2
    dns: <DNS server IP>

# mongoseed:
#   image: mongo
#   container_name: mongoseed
#   volumes:
#     - ./mongoDB/init:/init
#   command: mongoimport --host mongodb --db diplomatic_db --collection col
#     --jsonArray --file /init/init.json && python3 /init/db_monitor.py
#   depends_on:
#     - mongodb
