version: "3"
#make sure preferences no comma last
services:

  workload:
    container_name: 'workload'
    build: ./workload
    environment:
      PYTHONUNBUFFERED: 1
      Edges: ${workload_edges}
      Images: ${workload_edges_sleeps}
      Sleep: ${workload_edges_sleeps}
      Monitor_sleep: ${workload_sleep}
    dns: <DNS server IP>
    volumes:
      - ./volume/workload/log:/app/log
      - ./volume/workload/stats:/app/stats
