version: "3"

services:
  # models are fasterrcnn_mobilenet_v3_large_320_fpn, fasterrcnn_mobilenet_v3_large_fpn, fasterrcnn_resnet50_f retinanet_resnet50_fpn, maskrcnn_resnet50_fpn
  cloud:
    container_name: cloud
    build: ./cloud
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 1
      Monitor_sleep: ${sleep_cloud}
    dns: <DNS server IP>
    volumes:
      - ./volume/cloud/log:/app/log
      - ./volume/cloud/stats:/app/stats

  edge1:
    container_name: edge1
    build: ./edge
    ports:
      - "5001:5001"
    environment:
      PYTHONUNBUFFERED: 1
      ML: ${edge1_ml}
      Preprocessing: ${edge1_pre}
      Name: edge1
      Monitor_sleep: ${edge1_sleep}
    depends_on:
      - cloud
    dns: <DNS server IP>
    volumes:
      - ./volume/edges/log:/app/log
      - ./volume/edges/stats:/app/stats

  edge2:
    container_name: edge2
    build: ./edge
    ports:
      - "5002:5002"
    environment:
      PYTHONUNBUFFERED: 1
      ML: ${edge2_ml}
      Preprocessing: ${edge2_pre}
      Name: edge2
      Monitor_sleep: ${edge2_sleep}
    depends_on:
      - cloud
    dns: <DNS server IP>
    volumes:
      - ./volume/edges/log:/app/log
      - ./volume/edges/stats:/app/stats

  workload:
    container_name: workload
    build: ./workload
    depends_on:
      - cloud
    environment:
      PYTHONUNBUFFERED: 1
      Edges: ${workload_edges}
      Images: ${workload_num_of_images}
      Monitor_sleep: ${workload_sleep}
    dns: <DNS server IP>
    volumes:
      - ./volume/workload/log:/app/log
      - ./volume/workload/stats:/app/stats
